custom_functions:
  dir: /opt/stockpush/stockpush/userfunc
  functions:
  - desc: MF30多因子信号
    dir: /opt/stockpush/stockpush/userfunc
    file: MF30.py
    func: MF30
    name: MF30
  - desc: 5分分钟预警
    dir: /opt/stockpush/stockpush/userfunc
    file: MF05.py
    func: MF05
    name: MF05
  - desc: TF05双均线SID状态字节(5M)
    dir: /opt/stockpush/stockpush/userfunc
    file: TF05.py
    func: TF05
    name: TF05
  - desc: TF05双均线SID状态字节(30M)
    dir: /opt/stockpush/stockpush/userfunc
    file: TF05.py
    func: TF05
    name: TF05_30M
datasources:
  primary: xtick
feishu:
  enabled: true
  sign_enabled: false
  sign_secret: ""
  webhook: ""
schedule:
  afternoon_end: '15:05'
  afternoon_start: '13:00:05'
  interval_seconds: 60
  morning_end: '11:35'
  morning_start: 09:25
